import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/db';
import { tags } from '@/db/schema';
import { eq } from 'drizzle-orm';
import QRCode from 'qrcode';
import jsPDF from 'jspdf';

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ slug: string }> }
) {
  const { slug } = await params;

  const tag = await db.query.tags.findFirst({
    where: eq(tags.slug, slug),
  });

  if (!tag) {
    return NextResponse.json({ error: 'Tag not found' }, { status: 404 });
  }

  const baseUrl = process.env.BETTER_AUTH_URL || 'http://localhost:3000';
  const qrUrl = `${baseUrl}/p/${slug}`;

  // Generate QR Code
  const qrCode = await QRCode.toDataURL(qrUrl, {
    width: 300,
    margin: 2,
    color: {
      dark: '#1f2937',
      light: '#ffffff',
    },
  });

  // Generate PDF
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // Title
  pdf.setFontSize(20);
  pdf.setTextColor(31, 41, 55);
  pdf.text(tag.tier === 'premium' ? 'Balikin - Premium QR Tag' : 'Balikin - Digital Tag Free', pageWidth / 2, 25, { align: 'center' });

  // Tag name
  pdf.setFontSize(14);
  pdf.setTextColor(75, 85, 99);
  pdf.text(tag.name, pageWidth / 2, 40, { align: 'center' });

  if (tag.tier !== 'premium') {
    pdf.setFontSize(10);
    pdf.setTextColor(37, 99, 235);
    pdf.text('Protected by Balikin Free', pageWidth / 2, 48, { align: 'center' });
  }

  // Add QR code image
  const qrSize = 100;
  const qrX = (pageWidth - qrSize) / 2;
  pdf.addImage(qrCode, 'PNG', qrX, 55, qrSize, qrSize);

  // URL
  pdf.setFontSize(10);
  pdf.setTextColor(107, 114, 128);
  pdf.text(qrUrl, pageWidth / 2, 165, { align: 'center' });

  // Instructions
  pdf.setFontSize(11);
  pdf.setTextColor(31, 41, 55);
  pdf.text('Cara Penggunaan:', 20, 185);
  pdf.setFontSize(9);
  pdf.setTextColor(75, 85, 99);
  const instructions = [
    '1. Cetak QR code ini',
    '2. Gunakan sebagai aset DIY atau tempel mandiri pada barang Anda',
    '3. Jika barang hilang, penemu dapat memindai QR code',
    '4. Penemu dapat menghubungi Anda via WhatsApp'
  ];
  instructions.forEach((instruction, i) => {
    pdf.text(instruction, 25, 192 + (i * 6));
  });

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(156, 163, 175);
  pdf.text(
    tag.tier === 'premium' ? 'Generated by Balikin.app' : 'Generated by Balikin Free',
    pageWidth / 2,
    pageHeight - 10,
    { align: 'center' }
  );

  // Return PDF
  const pdfBuffer = Buffer.from(pdf.output('arraybuffer'));

  return new NextResponse(pdfBuffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="balikin-${tag.slug}.pdf"`,
    },
  });
}
