import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // Balikin Gold Theme Colors
        tertiary: {
          DEFAULT: "#00f1ff",
          container: "#006a70",
        },
        "surface-container": "#231f14",
        "status-critical": "#FF4D4D",
        "on-error": "#690005",
        "data-mask-overlay": "rgba(255, 255, 255, 0.05)",
        "on-surface": "#eae2cf",
        "inverse-surface": "#eae2cf",
        "on-secondary": "#313030",
        "on-tertiary": "#00363a",
        "on-primary": "#3a3000",
        "surface-dim": "#161308",
        "on-secondary-fixed-variant": "#474646",
        "tertiary": "#defcff",
        "primary-fixed": "#ffe16d",
        "on-secondary-fixed": "#1c1b1b",
        "surface-deep": "#0A0A0A",
        "status-resolved": "#00E676",
        "surface-variant": "#393528",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#c8c6c5",
        "outline-variant": "#4d4732",
        "surface-container-high": "#2e2a1e",
        "on-background": "#eae2cf",
        "inverse-on-surface": "#343024",
        "on-tertiary-container": "#006a70",
        "on-tertiary-fixed": "#002022",
        "surface-bright": "#3d392c",
        "surface-container-lowest": "#110e05",
        "tertiary-fixed-dim": "#00dbe8",
        "surface-tint": "#e9c400",
        "balikin-gold": "#FFD700",
        "surface-container-low": "#1f1b10",
        "primary-fixed-dim": "#e9c400",
        "primary-container": "#ffd700",
        error: "#ffb4ab",
        "premium-badge": "#FFD700",
        "secondary-container": "#4a4949",
        "on-primary-fixed-variant": "#544600",
        "on-error-container": "#ffdad6",
        surface: "#161308",
        "on-primary-fixed": "#221b00",
        "tertiary-fixed": "#79f5ff",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed-variant": "#004f54",
        "on-secondary-container": "#bab8b7",
        "status-open": "#2979FF",
        "surface-container-highest": "#393528",
        secondary: "#c8c6c5",
        primary: "#fff6df",
        "on-primary-container": "#705e00",
        "on-surface-variant": "#d0c6ab",
        "inverse-primary": "#705d00",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        DEFAULT: "0.25rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "sidebar-width": "280px",
        "gutter-md": "1.5rem",
        "container-padding": "2rem",
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["36px", { lineHeight: "44px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
